// Synced from my-money-v2 (src/lib/expenses/expenses-data.ts). Do not edit here: change it
// in the web repo and run `npm run sync:web`.
export const spendingOverview = {
  month: "May",
  total: 2129.4,
  dailyAverage: 70.98,
  transactionCount: 42,
  budgetLeft: 1520,
  delta: "+8% vs. April",
  note: "5 days remaining in May",
} as const;

export const spendingCategories = [
  {
    id: "rent",
    name: "Rent",
    description: "38% of monthly spending",
    amount: 1200,
    percent: 56.4,
    tone: "plum",
    count: 1,
    flag: null,
  },
  {
    id: "groceries",
    name: "Groceries",
    description: "13% · 8 visits",
    amount: 412,
    percent: 19.4,
    tone: "coral",
    count: 8,
    flag: null,
  },
  {
    id: "eating-out",
    name: "Eating out",
    description: "9% · up $54 vs. April",
    amount: 286,
    percent: 13.4,
    tone: "amber",
    count: 11,
    flag: "trending",
  },
  {
    id: "transport",
    name: "Transport",
    description: "6% · gas & transit",
    amount: 184,
    percent: 8.6,
    tone: "sage",
    count: 6,
    flag: null,
  },
  {
    id: "subscriptions",
    name: "Subscriptions",
    description: "2% · 4 active",
    amount: 47.4,
    percent: 2.2,
    tone: "ink",
    count: 4,
    flag: null,
  },
] as const;

export const spendingTrend = [
  { month: "Dec", spending: 1780 },
  { month: "Jan", spending: 1925 },
  { month: "Feb", spending: 1840 },
  { month: "Mar", spending: 2055 },
  { month: "Apr", spending: 1971 },
  { month: "May", spending: 2129 },
] as const;

export const spendingTransactions = [
  {
    id: "txn-whole-foods",
    merchant: "Whole Foods Market",
    note: "Brooklyn, NY",
    category: "Groceries",
    card: "Plum · 4821",
    date: "Today · 14:22",
    amount: 84.2,
  },
  {
    id: "txn-blue-bottle",
    merchant: "Blue Bottle",
    note: "Williamsburg",
    category: "Eating out",
    card: "Plum · 4821",
    date: "Today · 08:14",
    amount: 6.5,
  },
  {
    id: "txn-spotify",
    merchant: "Spotify",
    note: "Recurring · monthly",
    category: "Subscriptions",
    card: "Coral · 1937",
    date: "Yesterday · 06:30",
    amount: 10.99,
  },
  {
    id: "txn-citi-bike",
    merchant: "Citi Bike",
    note: "Annual membership",
    category: "Transport",
    card: "Plum · 4821",
    date: "May 4 · 17:08",
    amount: 24,
  },
  {
    id: "txn-robertas",
    merchant: "Roberta's Pizza",
    note: "Bushwick",
    category: "Eating out",
    card: "Coral · 1937",
    date: "May 4 · 20:42",
    amount: 48,
  },
  {
    id: "txn-delta",
    merchant: "Delta Airlines",
    note: "JFK to LAX",
    category: "Travel",
    card: "Plum · 4821",
    date: "May 1 · 11:42",
    amount: 310,
  },
  {
    id: "txn-trader-joes",
    merchant: "Trader Joe's",
    note: "Brooklyn, NY",
    category: "Groceries",
    card: "Plum · 4821",
    date: "Apr 29 · 18:04",
    amount: 52.3,
  },
  {
    id: "txn-coned",
    merchant: "ConEd",
    note: "Electric · monthly",
    category: "Utilities",
    card: "Direct debit",
    date: "Apr 28 · 09:00",
    amount: 72,
  },
  {
    id: "txn-target",
    merchant: "Target",
    note: "Household supplies",
    category: "Other",
    card: "Charcoal · 0094",
    date: "Apr 27 · 16:20",
    amount: 63.74,
  },
  {
    id: "txn-mta",
    merchant: "MTA",
    note: "MetroCard refill",
    category: "Transport",
    card: "Plum · 4821",
    date: "Apr 26 · 07:50",
    amount: 33,
  },
  {
    id: "txn-netflix",
    merchant: "Netflix",
    note: "Recurring · monthly",
    category: "Subscriptions",
    card: "Coral · 1937",
    date: "Apr 25 · 06:30",
    amount: 15.49,
  },
  {
    id: "txn-sweetgreen",
    merchant: "Sweetgreen",
    note: "Lunch",
    category: "Eating out",
    card: "Plum · 4821",
    date: "Apr 24 · 12:18",
    amount: 17.8,
  },
] as const;
